app/controllers/facilities_controller.rb, app/views/pages/home.html.erb, config/routes.rb, test/controllers/facilities_controller_test.rb
facilities controller, simple first step, can merge maybe
=> Controller facilities

app/controllers/cities_controller.rb, app/controllers/users_controller.rb, test/controllers/cities_controller_test.rb, test/controllers/users_controller_test.rb
=> Controller users

app/controllers/features_controller.rb, test/controllers/features_controller_test.rb
=> FEAT: featrues controller create

app/controllers/reviews_controller.rb, test/controllers/reviews_controller_test.rb
=> FEAT: reviews controller created

db/migrate/20190820124728_add_country_to_cities.rb, db/schema.rb
=> Added country to cities

app/controllers/facilities_controller.rb
=> FEAT: search feature for facilities controller

app/views/pages/home.html.erb, config/routes.rb
We created a form for search in the home.html.erb
=> FEAT: search form created

db/seeds.rb
Cities have now also countries in the seed
=> added country to seed

app/controllers/facilities_controller.rb, app/controllers/pages_controller.rb, app/views/facilities/index.html.erb, app/views/pages/home.html.erb, config/routes.rb, db/seeds.rb
search with simple form, dropdown list instead of radio button.
=> FEAT: search form with a dropdown category

app/controllers/pages_controller.rb
=> FIX: search really works now

app/models/category.rb, app/models/city.rb, app/models/facility.rb, app/models/feature.rb, app/models/feature_category.rb, app/models/feature_facility.rb, app/models/review.rb, app/models/user.rb
We created the validation on the models, and checked with Marin the dependencies between table again.
=> validations created

app/views/facilities/index.html.erb
I add a link commented out for the show page, it s on the same line as the name so as long as we don't comment it out the name will not appear
=> FEAT: link to home and add a facility added to the index view page

app/controllers/facilities_controller.rb, app/views/pages/home.html.erb
=> FIX: search still has some problem, fix tomorrow

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/config/_colors.scss, app/controllers/facilities_controller.rb, app/views/facilities/new.html.erb, app/views/facilities/show.html.erb
=> showpage unfinished

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/show.scss, app/controllers/reviews_controller.rb, app/views/facilities/show.html.erb
Some styling added, will return to this when review is working
=> Showpage styling vol2

app/controllers/application_controller.rb, app/controllers/facilities_controller.rb, app/controllers/pages_controller.rb, app/models/user.rb, app/views/facilities/index.html.erb, app/views/facilities/new.html.erb, config/routes.rb
=> link add pimped  in the index

app/assets/stylesheets/components/_indexlayout.scss
Corrected mistake done by resolving conflict
=> added missing bracket

app/views/facilities/index.html.erb
syntax error fixed please merge!
=> FIX: syntax error in index fixed

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/facilities_controller.rb, app/policies/application_policy.rb, app/policies/facility_policy.rb, test/policies/facility_policy_test.rb
Pundit set up made.
Let s be prudent about the merge, see if anything brake or not
=> pundit set up made with all authorization created

app/controllers/facilities_controller.rb, app/views/facilities/index.html.erb, config/routes.rb
Create new per category working from index per category.
=> Create new working from index

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
=> FEAT: style for the slide

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
=> Slide style

app/views/shared/_navbar.html.erb, config/routes.rb
=> FEAT: log out works

app/controllers/reviews_controller.rb, app/policies/review_policy.rb, config/routes.rb, db/seeds.rb, test/policies/review_policy_test.rb
i added the punfit for review, so nw it s working perfectly.
I pushed thursday night around 22h45, no worries to have about this branch been pulled request hours before when you will look at it today.
=> pundit for review done

app/assets/stylesheets/pages/_home.scss
changed a bit the box shadow style
=> FEAT: homepage box shadow retouched

app/models/category.rb, app/views/facilities/index.html.erb, db/migrate/20190823092624_add_photo_to_category.rb, db/schema.rb, db/seeds.rb
=> FEAT: add cloundinary photo for each category

app/assets/stylesheets/components/_indexlayout.scss, app/javascript/functions/slideout.js, app/views/shared/_navbar.html.erb
we do cool things with JavaScript ..... with the help of Marin lol
=> FEAT: now we have a cool slide and navbar lol

app/controllers/cities_controller.rb
Thomas fixed a small issue on authorisation
=> Pundit working for city

Gemfile, app/controllers/facilities_controller.rb, app/javascript/packs/application.js, app/javascript/plugins/init_mapbox.js, app/models/facility.rb, app/views/facilities/show.html.erb, app/views/layouts/application.html.erb, config/initializers/geocoder.rb, package.json, yarn.lock
I created a map and displayed it in the show method
=> FEAT : map created and displayed in show

app/views/layouts/application.html.erb, db/schema.rb
changed the page title into FamTravel
=> FEAT: changed the page name

app/assets/stylesheets/components/_footer.scss, db/schema.rb
=> FEAT: sticky bottom done

app/assets/stylesheets/pages/_show.scss, app/controllers/facilities_controller.rb, app/views/facilities/show.html.erb
Country still missing from user
=> Added writer and some style to review on show

app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_profile.scss, app/javascript/functions/js_tabs.js, app/javascript/packs/application.js, app/views/users/show.html.erb
=> Profile page working with three tabs

app/views/pages/home.html.erb
FEAT: dropdown search implemented to the home page
=> FEAT: dropdown search implemented to the home page

app/controllers/facilities_controller.rb, app/models/facility.rb, app/views/facilities/index.html.erb
user distance added, remember when push to HEROKU need to REMOVE THE FAKE IP ADDRESS!!!
=> FEAT: user distance added

app/assets/stylesheets/components/_shareyourtip.scss, app/controllers/facilities_controller.rb, app/views/users/show.html.erb
button from home page return to the home page if nothing is choose
=> Homepagesearchbuttonwithoutinput

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_footer.scss, app/javascript/functions/slideout.js, app/views/facilities/index.html.erb, app/views/facilities/show.html.erb, app/views/shared/_navbar.html.erb
=> Frontend wed

app/views/facilities/new.html.erb
And added name of the category in label
=> Changed add city to the beginning of the form

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_show.scss, app/views/facilities/index.html.erb
=> Frontend wed1

app/views/facilities/maps.html.erb
FEAT: back button created for the map for the index
=> FEAT: back button created for the map for the index

app/assets/stylesheets/components/_cards.scss
the stars distance in the card in index is fixed!
=> FIX: the stars
